# Generated by Django 5.0.7 on 2026-03-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0003_job_resultfile_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='download_button_id',
            field=models.CharField(blank=True, default='download', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='download_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='password_field',
            field=models.CharField(blank=True, default='pass', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='username_field',
            field=models.CharField(blank=True, default='userid', max_length=50),
        ),
    ]
